on:
  push:
    branches-ignore:
      - 'master'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install Npm"
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: "Install build dependencies"
        run: npm install
      - name: "Build the static files"
        run: npm run-script build
